# Copilot: ResourceQuota for default namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
spec:
  hard:
    pods: "20"
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
