name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run tests
      run: mvn test

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest ./user-service
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest ./product-service
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest ./order-service
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:latest ./gateway-service
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:latest
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/config-server:latest ./config-server
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/config-server:latest
        docker build -t $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest ./discovery-server
        docker push $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/user-service user-service=$REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
        kubectl set image deployment/product-service product-service=$REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
        kubectl set image deployment/order-service order-service=$REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
        kubectl set image deployment/gateway-service gateway-service=$REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:latest
        kubectl set image deployment/config-server config-server=$REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/config-server:latest
        kubectl set image deployment/discovery-server discovery-server=$REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest
